# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Pete\Documents\cc3d\cc3d-player5\cc3d\player5\Plugins\ViewManagerPlugins\ui_demo_browser.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_demoDialog(object):
    def setupUi(self, demoDialog):
        demoDialog.setObjectName("demoDialog")
        demoDialog.setWindowModality(QtCore.Qt.NonModal)
        demoDialog.resize(541, 424)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(demoDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.v_layout = QtWidgets.QVBoxLayout()
        self.v_layout.setObjectName("v_layout")
        self.searchLineEdit = QtWidgets.QLineEdit(demoDialog)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.v_layout.addWidget(self.searchLineEdit)
        self.demoResultsScrollArea = QtWidgets.QScrollArea(demoDialog)
        self.demoResultsScrollArea.setWidgetResizable(True)
        self.demoResultsScrollArea.setObjectName("demoResultsScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 519, 150))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.demoListView = QtWidgets.QListView(self.scrollAreaWidgetContents)
        self.demoListView.setObjectName("demoListView")
        self.horizontalLayout_2.addWidget(self.demoListView)
        self.demoResultsScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.v_layout.addWidget(self.demoResultsScrollArea)
        self.demoTreeView = QtWidgets.QTreeView(demoDialog)
        self.demoTreeView.setObjectName("demoTreeView")
        self.v_layout.addWidget(self.demoTreeView)
        self.demoDescriptionLabel = QtWidgets.QLabel(demoDialog)
        self.demoDescriptionLabel.setObjectName("demoDescriptionLabel")
        self.v_layout.addWidget(self.demoDescriptionLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.v_layout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.v_layout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.v_layout)
        self.buttonBox = QtWidgets.QDialogButtonBox(demoDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Open)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(demoDialog)
        QtCore.QMetaObject.connectSlotsByName(demoDialog)

    def retranslateUi(self, demoDialog):
        _translate = QtCore.QCoreApplication.translate
        demoDialog.setWindowTitle(_translate("demoDialog", "Demo Browser"))
        self.searchLineEdit.setPlaceholderText(_translate("demoDialog", "Search..."))
        self.demoDescriptionLabel.setText(_translate("demoDialog", "TextLabel"))
