# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'movie_generator_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MovieGeneratorDialog(object):
    def setupUi(self, MovieGeneratorDialog):
        MovieGeneratorDialog.setObjectName("MovieGeneratorDialog")
        MovieGeneratorDialog.resize(691, 268)
        self.verticalLayout = QtWidgets.QVBoxLayout(MovieGeneratorDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(MovieGeneratorDialog)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.ffmpeg_path_LE = QtWidgets.QLineEdit(MovieGeneratorDialog)
        self.ffmpeg_path_LE.setObjectName("ffmpeg_path_LE")
        self.horizontalLayout_2.addWidget(self.ffmpeg_path_LE)
        self.pushButton = QtWidgets.QPushButton(MovieGeneratorDialog)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(MovieGeneratorDialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.simulation_output_folder = QtWidgets.QLineEdit(MovieGeneratorDialog)
        self.simulation_output_folder.setObjectName("simulation_output_folder")
        self.horizontalLayout_4.addWidget(self.simulation_output_folder)
        self.generate_movies_PB = QtWidgets.QPushButton(MovieGeneratorDialog)
        self.generate_movies_PB.setObjectName("generate_movies_PB")
        self.horizontalLayout_4.addWidget(self.generate_movies_PB)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(MovieGeneratorDialog)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.frame_rate_SB = QtWidgets.QSpinBox(MovieGeneratorDialog)
        self.frame_rate_SB.setMinimum(1)
        self.frame_rate_SB.setMaximum(120)
        self.frame_rate_SB.setProperty("value", 4)
        self.frame_rate_SB.setObjectName("frame_rate_SB")
        self.horizontalLayout_6.addWidget(self.frame_rate_SB)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(MovieGeneratorDialog)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.quality_SB = QtWidgets.QSpinBox(MovieGeneratorDialog)
        self.quality_SB.setMinimum(1)
        self.quality_SB.setMaximum(10)
        self.quality_SB.setProperty("value", 7)
        self.quality_SB.setObjectName("quality_SB")
        self.horizontalLayout_7.addWidget(self.quality_SB)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        self.mcs_on_frame_CB = QtWidgets.QCheckBox(MovieGeneratorDialog)
        self.mcs_on_frame_CB.setChecked(True)
        self.mcs_on_frame_CB.setObjectName("mcs_on_frame_CB")
        self.horizontalLayout_8.addWidget(self.mcs_on_frame_CB)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        spacerItem = QtWidgets.QSpacerItem(20, 90, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.status_LB = QtWidgets.QLabel(MovieGeneratorDialog)
        self.status_LB.setObjectName("status_LB")
        self.verticalLayout.addWidget(self.status_LB)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.ok_PB = QtWidgets.QPushButton(MovieGeneratorDialog)
        self.ok_PB.setObjectName("ok_PB")
        self.horizontalLayout_5.addWidget(self.ok_PB)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(MovieGeneratorDialog)
        self.ok_PB.clicked.connect(MovieGeneratorDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MovieGeneratorDialog)

    def retranslateUi(self, MovieGeneratorDialog):
        _translate = QtCore.QCoreApplication.translate
        MovieGeneratorDialog.setWindowTitle(_translate("MovieGeneratorDialog", "Generate Simulation Movies"))
        self.label.setText(_translate("MovieGeneratorDialog", "Path to FFMPEG Executable"))
        self.pushButton.setText(_translate("MovieGeneratorDialog", "Detect FFMPEG"))
        self.label_4.setText(_translate("MovieGeneratorDialog", "Select Simulation Output Folder"))
        self.generate_movies_PB.setText(_translate("MovieGeneratorDialog", "Generate Movies"))
        self.label_5.setText(_translate("MovieGeneratorDialog", "Frame Rate"))
        self.label_6.setText(_translate("MovieGeneratorDialog", "Quality (1=worst 10=best)"))
        self.mcs_on_frame_CB.setText(_translate("MovieGeneratorDialog", "Write MCS on each frame"))
        self.status_LB.setText(_translate("MovieGeneratorDialog", "Status Label"))
        self.ok_PB.setText(_translate("MovieGeneratorDialog", "Close"))
