# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simulation_settings_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SimulationSettingsDialog(object):
    def setupUi(self, SimulationSettingsDialog):
        SimulationSettingsDialog.setObjectName("SimulationSettingsDialog")
        SimulationSettingsDialog.resize(640, 210)
        self.verticalLayout = QtWidgets.QVBoxLayout(SimulationSettingsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sqliteLocationLabel = QtWidgets.QLabel(SimulationSettingsDialog)
        self.sqliteLocationLabel.setObjectName("sqliteLocationLabel")
        self.verticalLayout.addWidget(self.sqliteLocationLabel)
        self.sqliteLocationLineEdit = QtWidgets.QLineEdit(SimulationSettingsDialog)
        self.sqliteLocationLineEdit.setReadOnly(True)
        self.sqliteLocationLineEdit.setObjectName("sqliteLocationLineEdit")
        self.verticalLayout.addWidget(self.sqliteLocationLineEdit)
        self.xmlFormatCheckBox = QtWidgets.QCheckBox(SimulationSettingsDialog)
        self.xmlFormatCheckBox.setObjectName("xmlFormatCheckBox")
        self.verticalLayout.addWidget(self.xmlFormatCheckBox)
        self.xmlLocationLabel = QtWidgets.QLabel(SimulationSettingsDialog)
        self.xmlLocationLabel.setObjectName("xmlLocationLabel")
        self.verticalLayout.addWidget(self.xmlLocationLabel)
        self.xmlLocationLineEdit = QtWidgets.QLineEdit(SimulationSettingsDialog)
        self.xmlLocationLineEdit.setReadOnly(True)
        self.xmlLocationLineEdit.setObjectName("xmlLocationLineEdit")
        self.verticalLayout.addWidget(self.xmlLocationLineEdit)
        self.statusLabel = QtWidgets.QLabel(SimulationSettingsDialog)
        self.statusLabel.setText("")
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout.addWidget(self.statusLabel)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem)
        self.exportSettingsButton = QtWidgets.QPushButton(SimulationSettingsDialog)
        self.exportSettingsButton.setObjectName("exportSettingsButton")
        self.buttonLayout.addWidget(self.exportSettingsButton)
        self.deleteSettingsButton = QtWidgets.QPushButton(SimulationSettingsDialog)
        self.deleteSettingsButton.setObjectName("deleteSettingsButton")
        self.buttonLayout.addWidget(self.deleteSettingsButton)
        self.closeButton = QtWidgets.QPushButton(SimulationSettingsDialog)
        self.closeButton.setObjectName("closeButton")
        self.buttonLayout.addWidget(self.closeButton)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(SimulationSettingsDialog)
        self.closeButton.clicked.connect(SimulationSettingsDialog.close)
        QtCore.QMetaObject.connectSlotsByName(SimulationSettingsDialog)

    def retranslateUi(self, SimulationSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        SimulationSettingsDialog.setWindowTitle(_translate("SimulationSettingsDialog", "Manage Simulation Settings"))
        self.sqliteLocationLabel.setText(_translate("SimulationSettingsDialog", "SQLite settings:"))
        self.xmlFormatCheckBox.setText(_translate("SimulationSettingsDialog", "XML Format"))
        self.xmlLocationLabel.setText(_translate("SimulationSettingsDialog", "XML settings:"))
        self.exportSettingsButton.setText(_translate("SimulationSettingsDialog", "Export Settings"))
        self.deleteSettingsButton.setText(_translate("SimulationSettingsDialog", "Delete Settings"))
        self.closeButton.setText(_translate("SimulationSettingsDialog", "Close"))
