# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_screenshot_description_browser.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_screenshotDescriptionDialog(object):
    def setupUi(self, screenshotDescriptionDialog):
        screenshotDescriptionDialog.setObjectName("screenshotDescriptionDialog")
        screenshotDescriptionDialog.resize(600, 500)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(screenshotDescriptionDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.v_layout = QtWidgets.QVBoxLayout()
        self.v_layout.setObjectName("v_layout")
        self.label = QtWidgets.QLabel(screenshotDescriptionDialog)
        self.label.setObjectName("label")
        self.v_layout.addWidget(self.label)
        self.scr_list_LW = QtWidgets.QListWidget(screenshotDescriptionDialog)
        self.scr_list_LW.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.scr_list_LW.setObjectName("scr_list_LW")
        self.v_layout.addWidget(self.scr_list_LW)
        self.label_2 = QtWidgets.QLabel(screenshotDescriptionDialog)
        self.label_2.setObjectName("label_2")
        self.v_layout.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(20, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.v_layout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.delete_selected_PB = QtWidgets.QPushButton(screenshotDescriptionDialog)
        self.delete_selected_PB.setEnabled(False)
        self.delete_selected_PB.setObjectName("delete_selected_PB")
        self.horizontalLayout.addWidget(self.delete_selected_PB)
        self.clear_screenshots_PB = QtWidgets.QPushButton(screenshotDescriptionDialog)
        self.clear_screenshots_PB.setObjectName("clear_screenshots_PB")
        self.horizontalLayout.addWidget(self.clear_screenshots_PB)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.ok_PB = QtWidgets.QPushButton(screenshotDescriptionDialog)
        self.ok_PB.setObjectName("ok_PB")
        self.horizontalLayout.addWidget(self.ok_PB)
        self.v_layout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.v_layout)

        self.retranslateUi(screenshotDescriptionDialog)
        self.ok_PB.clicked.connect(screenshotDescriptionDialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(screenshotDescriptionDialog)

    def retranslateUi(self, screenshotDescriptionDialog):
        _translate = QtCore.QCoreApplication.translate
        screenshotDescriptionDialog.setWindowTitle(_translate("screenshotDescriptionDialog", "Screenshot Description Browser"))
        self.label.setText(_translate("screenshotDescriptionDialog", "Available Screenshot Labels"))
        self.label_2.setText(_translate("screenshotDescriptionDialog", "Screenshot Description"))
        self.delete_selected_PB.setText(_translate("screenshotDescriptionDialog", "Delete Selected Screenshot"))
        self.clear_screenshots_PB.setText(_translate("screenshotDescriptionDialog", "Clear Screenshots"))
        self.ok_PB.setText(_translate("screenshotDescriptionDialog", "OK"))
