# it may happen that standard conda-builder is extremely slow . IN this situation it is good idea to install mamba and boa
# boa is a fast builder that uses mamba. It also has conda mambabuild utility that replaces conda build. you can still use 
# meta.yaml files if you want just type conda mambabuild ... instead of conda build ...
# see https://boa-build.readthedocs.io/en/latest/mambabuild.html
# when building as standalone package uncomment line below and set version and build_number to proper values
#{% set version = "4.3.1" %}
#{% set build_number = "0" %}
#{% set python_version = "3.7" %}

{% set versions = load_file_data('versions.yaml', from_recipe_dir=True) %}

{% set version = versions.get('version') %}
{% set build_number = versions.get('build_number',0) %}
{% set numpy_version = versions.get('numpy_version') %}


package:
  name: cc3d-player5
  version: {{ version }}

about:
  home: https://compucell3d.org
  license: LGPL
  license_file: ../LICENSE.txt

extra:
  maintainers: T.J. Sego, Maciek Swat

source:
  # url: https://github.com/CompuCell3D/cc3d-player5/archive/master.tar.gz
  path: ../

build:
  number: {{ build_number }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python={{ python }}
    - setuptools

  run:
    - python={{ python }}
    # - numpy=1.18 # when building with conda mambabuild
    - cc3d={{ version }}
    - webcolors
    - requests
    - pyqt=5
    - pyqtgraph

test:
  imports:
    - sys
    - cc3d.player5
