{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}
{% set python_version = "3.7" %}

package:
  name: cc3d-player5
  version: {{ version }}

about:
  home: https://compucell3d.org
  license: LGPL
  license_file: ../LICENSE.txt

extra:
  maintainers: T.J. Sego, Maciek Swat

source:
  # url: https://github.com/CompuCell3D/cc3d-player5/archive/master.tar.gz
  path: ../

build:
  number: 2
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python={{ python_version }}
    - setuptools

  run:
    - python={{ python_version }}
    - cc3d={{ version }}
    - qscintilla2
    - webcolors
    - requests
    - pyqt=5.6 # [osx]
    - pyqt # [not osx]
    - pyqtgraph

test:
  imports:
    - sys
    - cc3d.player5
